environment: prod
domains:
  - bts-crew.com
  - www.bts-crew.com

smtp:
  host: smtp.gmail.com
  port: 587

logging:
  driver: stack

google-analytics-code: UA-150311689-2

resources:
  memory: '256Mi'
